"""Trained deep-learning spoof detector — the primary verdict source.

Wraps a Wav2Vec2-based audio-classification model fine-tuned specifically for
deepfake/synthetic-speech detection (real vs. fake), trained on human
recordings plus clips generated by ElevenLabs, Amazon Polly, Kokoro, Hume AI,
Speechify and Luvvoice. This replaces the hand-tuned heuristic as the thing
that actually decides "real or cloned"; the heuristic in risk_scoring.py is
retained alongside it as a signal-level explainability layer.

Model: garystafford/wav2vec2-deepfake-voice-detector (Apache-2.0),
itself a fine-tune of Gustking/wav2vec2-large-xlsr-deepfake-audio-classification.
Labels are {0: "real", 1: "fake"} and it expects 16 kHz mono audio.
"""

from __future__ import annotations

import logging
import threading
from dataclasses import dataclass, field

import numpy as np

from app.core.config import settings

logger = logging.getLogger(__name__)

_model = None
_feature_extractor = None
_load_lock = threading.Lock()
_load_failed = False

# The model card reports best accuracy on clips of roughly 2.5-13s, so longer
# audio is scored in windows and averaged rather than in one very long pass.
WINDOW_SECONDS = 10.0
MAX_WINDOWS = 3
MIN_RELIABLE_SECONDS = 2.5


@dataclass
class TrainedResult:
    available: bool
    fake_probability: float = 0.0
    real_probability: float = 0.0
    label: str = "unknown"
    windows_scored: int = 0
    window_probabilities: list[float] = field(default_factory=list)
    short_clip_warning: bool = False
    error: str | None = None


def _load():
    """Lazily load model + feature extractor once, shared across requests."""
    global _model, _feature_extractor, _load_failed

    if _model is not None or _load_failed:
        return

    with _load_lock:
        if _model is not None or _load_failed:
            return
        try:
            from transformers import AutoFeatureExtractor, AutoModelForAudioClassification

            logger.info("Loading trained detector %s ...", settings.trained_model_name)
            model = AutoModelForAudioClassification.from_pretrained(settings.trained_model_name)
            model.eval()
            _feature_extractor = AutoFeatureExtractor.from_pretrained(settings.trained_model_name)
            _model = model
            logger.info("Trained detector ready (labels: %s)", model.config.id2label)
        except Exception as exc:
            _load_failed = True
            logger.warning("Trained detector unavailable, falling back to heuristic: %s", exc)


def is_ready() -> bool:
    return _model is not None


def _label_indices(model) -> tuple[int, int]:
    """Resolve which logit index means real vs. fake, from the model config."""
    real_idx, fake_idx = 0, 1
    for idx, label in model.config.id2label.items():
        normalized = str(label).strip().lower()
        if normalized in ("real", "bonafide", "genuine", "human"):
            real_idx = int(idx)
        elif normalized in ("fake", "spoof", "synthetic", "deepfake"):
            fake_idx = int(idx)
    return real_idx, fake_idx


def predict(y: np.ndarray, sr: int) -> TrainedResult:
    if not settings.enable_trained_model:
        return TrainedResult(available=False, error="Trained model disabled by configuration.")

    _load()
    if _model is None or _feature_extractor is None:
        return TrainedResult(available=False, error="Trained model could not be loaded.")

    try:
        import torch

        duration = len(y) / sr
        window_len = int(WINDOW_SECONDS * sr)
        windows = [y[i : i + window_len] for i in range(0, len(y), window_len)][:MAX_WINDOWS]
        # Drop a trailing sliver that is too short to score meaningfully.
        windows = [w for w in windows if len(w) >= sr * 0.5] or [y]

        real_idx, fake_idx = _label_indices(_model)
        fake_probs: list[float] = []

        for window in windows:
            inputs = _feature_extractor(window, sampling_rate=sr, return_tensors="pt", padding=True)
            with torch.no_grad():
                logits = _model(**inputs).logits
            probs = torch.nn.functional.softmax(logits, dim=-1)[0]
            fake_probs.append(float(probs[fake_idx]))

        mean_fake = float(np.mean(fake_probs))
        return TrainedResult(
            available=True,
            fake_probability=round(mean_fake, 4),
            real_probability=round(1.0 - mean_fake, 4),
            label="fake" if mean_fake >= 0.5 else "real",
            windows_scored=len(fake_probs),
            window_probabilities=[round(p, 4) for p in fake_probs],
            short_clip_warning=duration < MIN_RELIABLE_SECONDS,
        )
    except Exception as exc:
        logger.exception("Trained detector inference failed")
        return TrainedResult(available=False, error=str(exc))
